### ISSUE TITLE
Migrate currency api to exchangeratesapi.io

### ISSUE THREAD

**Issue by kamontat** [deanishe/alfred-convert#76] opened 2020-09-03 04:00 UTC
Since https://exchangeratesapi.io didn't require any API key, it will easier on user to use.

**Comment by deanishe** [comment] 2020-09-03 09:09
Duplicate of #47.

> Migrate currency api to exchangeratesapi.io

Replacing openexchangerates.org with exchangeratesapi.io would be daft because it only supports a tiny number of exchange rates, and they're only updated once a day.

In any case, the workflow already fetches (a limited number of) exchange rates from exchangerate-api.com if no key for openexchangerates.org is set.

**Closed as completed by deanishe** 2020-09-03 09:09 UTC
Labels: duplicate, wontfix

**Comment by jimmykl** [comment] 2020-09-03 20:05
+1 for use of daft
