### ISSUE TITLE
.alfred3workflow should be .alfredworkflow?

### ISSUE THREAD

**Issue by benwoodward** [deanishe/alfred-convert#23] opened 2017-07-18 10:56 UTC
Hi Dean, 

Thanks for this plugin, I've been using it for years, and I was recently delighted to discover that you've added crypto conversions. Thanks!

Took me quite a while to figure out that I needed to rename the extension for it to install, is that deliberate?

**Comment by deanishe** [comment] 2017-07-18 12:30
> is that deliberate?

Yes. The `.alfred3workflow` extension is supported by Alfred 3 only. It's used in GitHub releases, as it's the only way to prevent workflows running under Alfred 2 from forever trying to install an incompatible update.

If your system doesn't recognise the extension, that's most likely because you still have Alfred 2 installed and your system is preferring its definition for Alfred workflow files over Alfred 3's (the former doesn't include the `.alfred3workflow` extension).

**Comment by cgjosephlee** [comment] 2017-08-29 03:51
I'm using 3.4.1 and Alfred still cannot recognize `.alfred3workflow` file. I manually edit to `.alfredworkflow` and it works! Does anything go wrong?

**Comment by deanishe** [comment] 2017-08-29 05:54
Same answer as above, tbh. 

If you don't have Alfred 2 installed, you can try rebuilding you Launch Services database.

Or just change the extension of the downloaded file to `.alfredworkflow`. 

Closing this issue, as it's not a bug with the workflow, and there's nothing I can realistically do to fix it.

**Closed by deanishe** 2017-08-29 05:54 UTC
